"""Collect experiments/*.json into docs/experiments.md tables."""
from __future__ import annotations
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
rows = []
for p in sorted((ROOT / "experiments").glob("*.json")):
    j = json.load(open(p))
    if "results" in j:  # latency benchmark
        continue
    rows.append(j)

def f(x, d=3):
    return "-" if x is None else (f"{x:.{d}f}" if isinstance(x, float) else str(x))

lines = ["# Experiment log (auto-generated by scripts/summarize.py)", "",
         "| experiment | dataset | model | mode | head | target | loss | acc | F1 | ECE | ECE(T) | Brier | NLL | p50 ms | p95 ms |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
for j in rows:
    acc = j.get("accuracy"); ece = j.get("ece"); ecec = j.get("ece_calibrated", (j.get("calibrated") or {}).get("ece"))
    lines.append("| " + " | ".join([j.get("experiment", ""), j.get("dataset", ""), str(j.get("model", "")).replace("Qwen/", ""),
                 j.get("mode", ""), j.get("head", ""), j.get("target", ""), j.get("loss", ""), f(acc), f(j.get("macro_f1")), f(ece), f(ecec),
                 f(j.get("brier")), f(j.get("nll")), f(j.get("latency_p50_ms"), 1), f(j.get("latency_p95_ms"), 1)]) + " |")
lat = []
for p in sorted((ROOT / "experiments").glob("exp007*.json")):
    j = json.load(open(p))
    lat.append(j)
if lat:
    lines += ["", "## Multi-question latency (p50 ms)", ""]
    counts = [1, 2, 4, 8, 16]
    lines.append("| experiment | mode | " + " | ".join(f"q={c}" for c in counts) + " |")
    lines.append("|---|---|" + "---|" * len(counts))
    for j in lat:
        modes = sorted({k.split("/")[0] for k in j["results"] if "/" in k})
        for m in modes:
            lines.append(f"| {j['experiment']} | {m} | " + " | ".join(f(j["results"].get(f"{m}/{c}", {}).get("p50"), 1) for c in counts) + " |")
per = [j for j in rows if "per_task" in j]
if per:
    lines += ["", "## Multi-task shared head: per-task test metrics", ""]
    for j in per:
        lines += [f"### {j['experiment']}", "", "| task | acc | F1 | ECE | Brier |", "|---|---|---|---|---|"]
        for t, m in j["per_task"].items():
            lines.append(f"| {t} | {f(m['accuracy'])} | {f(m['macro_f1'])} | {f(m['ece'])} | {f(m['brier'])} |")
        lines.append("")
out = ROOT / "docs/experiments.md"
out.write_text("\n".join(lines) + "\n")
print("\n".join(lines))
