"""画像に投げる質問セット (状態分類). build_vision_choices.py がテキスト側を計算して配る.

物体検出 (箱を出す) ではなく、場面の**状態**を有限の選択肢で答えさせる。
選択肢には「分からない」を入れられる。自信が無いときに作り話をせず、そう言えるのが売り。

prompts は英語で書く。SigLIP2 に日本語を直接入れると答えが反転することがある
(「散らかった机 / 片付いた机」で実測)。画面に出す label だけ日本語にする。
選択肢ごとに複数の言い方を持たせると平均されて安定する (昼と夜、寄りと引き、など)。
"""
from __future__ import annotations

from typing import Any

Q = dict[str, Any]


def q(key: str, title: str, *choices: tuple[str, str, list[str]], requires: tuple[str, list[str]] | None = None) -> Q:
    """requires=("isfood", ["yes"]) は「isfood が yes のときだけ答える」。

    質問は互いに独立に答えるので、前提が崩れていても平気で答えてしまう
    (食べ物が写っていないのに「和食」と言う)。前提を持たせて、崩れていれば答えない。
    """
    out: Q = {"key": key, "title": title,
              "choices": [{"id": cid, "label": label, "prompts": prompts} for cid, label, prompts in choices]}
    if requires:
        out["requires"] = {"key": requires[0], "any": list(requires[1])}
    return out


# ---------------------------------------------------------------- 1. 室内外の汎用
GENERAL = [
    q("tidy", "片付き具合",
      ("tidy", "片付いている", ["a tidy, organized desk or room", "a clean minimal room with everything in place"]),
      ("messy", "散らかっている", ["a messy, cluttered desk or room with scattered objects", "clothes and rubbish piled on the floor"])),
    q("light", "照明",
      ("on", "点いている", ["a room with the lights turned on, brightly lit", "a bright indoor scene"]),
      ("off", "消えている", ["a dark room with the lights turned off", "an unlit room at night"])),
    q("crowd", "混み具合",
      ("empty", "無人", ["an empty place with no people"]),
      ("few", "数人", ["a place with a few people"]),
      ("crowded", "混雑", ["a crowded place packed with many people"])),
    q("wet", "路面・床",
      ("dry", "乾いている", ["a dry road or floor surface"]),
      ("wet", "濡れている", ["a wet road or floor surface with puddles", "rain soaked pavement with reflections"]),
      ("snow", "雪", ["a road or ground covered with snow"])),
    q("door", "扉",
      ("open", "開いている", ["a door that is open"]),
      ("closed", "閉まっている", ["a door that is closed"]),
      ("nodoor", "扉が写っていない", ["a scene without any door"])),
    q("screen", "画面の状態",
      ("normal", "正常に表示", ["a computer screen showing a normal working application"]),
      ("error", "エラー表示", ["a computer screen showing an error message or a warning dialog"]),
      ("off", "消灯・真っ暗", ["a computer screen that is turned off or black"])),
    q("weather", "天気 (屋外)",
      ("sunny", "晴れ", ["an outdoor scene on a sunny day with blue sky"]),
      ("cloudy", "曇り", ["an outdoor scene on a cloudy overcast day"]),
      ("rain", "雨", ["an outdoor scene in the rain, wet and grey"]),
      ("night", "夜", ["an outdoor scene at night, dark"])),
    q("place", "場所",
      ("indoor", "屋内", ["an indoor scene inside a building"]),
      ("outdoor", "屋外", ["an outdoor scene outside"])),
    q("work", "設備の状態",
      ("running", "稼働中", ["machinery or equipment that is running and in operation"]),
      ("idle", "停止中", ["machinery or equipment that is stopped and idle"]),
      ("none", "設備が写っていない", ["a scene with no machinery"])),
    q("shelf", "棚・在庫",
      ("full", "十分ある", ["store shelves fully stocked with products"]),
      ("low", "少ない", ["store shelves that are nearly empty, low stock"]),
      ("none", "棚が写っていない", ["a scene that does not show any shelves"])),
]

# ---------------------------------------------------------------- 2. 人物の様子
PEOPLE = [
    q("present", "人が写っているか",
      ("yes", "写っている", ["a photo of a person", "a portrait of someone"]),
      ("no", "写っていない", ["a scene with no people at all", "an empty room with nobody"])),
    q("count", "人数",
      ("one", "1 人", ["a photo of a single person alone"]),
      ("few", "2-3 人", ["a photo of two or three people together"]),
      ("many", "4 人以上", ["a group photo of many people", "a crowd of people"]),
      requires=("present", ['yes'])),
    q("age", "年齢層",
      ("child", "子供", ["a photo of a young child", "a little kid"]),
      ("teen", "10 代", ["a photo of a teenager", "a high school student"]),
      ("adult", "20-50 代", ["a photo of an adult in their thirties", "a working age adult"]),
      ("senior", "高齢", ["a photo of an elderly person with grey hair", "an old man or old woman"]),
      requires=("present", ['yes'])),
    q("gender", "性別の見え方",
      ("male", "男性に見える", ["a photo of a man", "a male person"]),
      ("female", "女性に見える", ["a photo of a woman", "a female person"]),
      requires=("present", ['yes'])),
    q("expression", "表情",
      ("smile", "笑顔", ["a person smiling happily", "a big grin"]),
      ("neutral", "真顔", ["a person with a neutral expression", "a straight face"]),
      ("sad", "沈んでいる", ["a sad or worried face", "someone looking down"]),
      ("surprised", "驚き", ["a surprised face with wide eyes"]),
      requires=("present", ['yes'])),
    q("glasses", "眼鏡",
      ("yes", "かけている", ["a person wearing glasses"]),
      ("no", "かけていない", ["a person without glasses"]),
      requires=("present", ['yes'])),
    q("mask", "マスク",
      ("yes", "している", ["a person wearing a face mask covering nose and mouth"]),
      ("no", "していない", ["a person with an uncovered face"]),
      requires=("present", ['yes'])),
    q("hat", "帽子",
      ("yes", "かぶっている", ["a person wearing a hat or cap"]),
      ("no", "かぶっていない", ["a person with no hat, bare head"]),
      requires=("present", ['yes'])),
    q("pose", "向き",
      ("front", "正面", ["a person facing the camera directly"]),
      ("side", "横向き", ["a person seen from the side, profile view"]),
      ("back", "後ろ向き", ["a person seen from behind, back turned"]),
      requires=("present", ['yes'])),
]

# ---------------------------------------------------------------- 3. ゲーム画面の状態
#: 自動操作で難しいのは操作そのものより「いまどの画面か」の判定。そこだけを有限の選択肢で答える
GAME = [
    q("isgame", "ゲーム画面か",
      ("yes", "ゲーム画面", ["a screenshot of a video game", "a game being played on a screen"]),
      ("no", "ゲームではない", ["a photo of an ordinary scene, not a game", "a desktop application window"])),
    q("screen", "画面の種類",
      ("title", "タイトル・開始前", ["a video game title screen with a start button", "a game main menu screen"]),
      ("play", "プレイ中", ["in-game action gameplay with the character moving"]),
      ("menu", "メニュー・設定", ["a game settings or inventory menu with a list of options"]),
      ("loading", "ロード中", ["a loading screen with a progress bar", "a black screen with the word loading"]),
      ("result", "結果・リザルト", ["a game result screen showing a score and rank"]),
      requires=("isgame", ['yes'])),
    q("outcome", "勝敗",
      ("win", "勝ち・クリア", ["a victory screen saying you win, stage clear"]),
      ("lose", "負け・ゲームオーバー", ["a game over screen, you died"]),
      ("none", "決着していない", ["ordinary gameplay with no result banner"]),
      requires=("isgame", ['yes'])),
    q("view", "視点",
      ("fps", "一人称", ["a first person shooter view with a gun in the foreground"]),
      ("third", "三人称", ["a third person view following a character from behind"]),
      ("top", "見下ろし・横視点", ["a top down or side scrolling 2D game view"]),
      requires=("isgame", ['yes'])),
    q("style", "見た目",
      ("realistic", "実写的な 3D", ["a photorealistic 3D game with detailed lighting"]),
      ("anime", "アニメ調", ["an anime style game with cel shaded characters"]),
      ("pixel", "ドット絵・レトロ", ["a pixel art retro game screen"]),
      requires=("isgame", ['yes'])),
    q("hud", "情報表示",
      ("hud", "ゲージや数字が出ている", ["a game screen with a health bar, minimap and score overlay"]),
      ("clean", "何も出ていない", ["a clean screen without any interface overlay"]),
      requires=("isgame", ['yes'])),
    q("dialog", "ポップアップ",
      ("dialog", "ダイアログが出ている", ["a modal dialog box with buttons on a game screen", "a pop up asking to confirm"]),
      ("none", "出ていない", ["a game screen with no pop up window"]),
      requires=("isgame", ['yes'])),
    q("crowded", "画面の密度",
      ("busy", "情報が多い", ["a busy cluttered game screen with many icons and numbers"]),
      ("simple", "すっきり", ["a simple sparse game screen with few elements"]),
      requires=("isgame", ['yes'])),
]

# ---------------------------------------------------------------- 4. 食べ物
FOOD = [
    q("isfood", "食べ物か",
      ("yes", "食べ物", ["a photo of food on a plate", "a meal ready to eat"]),
      ("no", "食べ物ではない", ["a scene with no food"])),
    q("genre", "ジャンル",
      ("japanese", "和食", ["japanese food, rice bowl and miso soup", "sushi and sashimi"]),
      ("western", "洋食", ["western food, steak or pasta on a plate", "a hamburger and fries"]),
      ("chinese", "中華", ["chinese food, fried rice or dumplings"]),
      ("sweet", "デザート", ["a dessert, cake or parfait", "ice cream and sweets"]),
      requires=("isfood", ['yes'])),
    q("state", "食べ具合",
      ("fresh", "手つかず", ["a full untouched plate of food, freshly served"]),
      ("eating", "食べかけ", ["a half eaten meal, partly finished"]),
      ("empty", "食べ終わり", ["an empty plate with only crumbs left"]),
      requires=("isfood", ['yes'])),
    q("temp", "温度感",
      ("hot", "温かい料理", ["a hot steaming dish with visible steam"]),
      ("cold", "冷たい料理", ["a cold dish, salad or chilled dessert"]),
      requires=("isfood", ['yes'])),
    q("volume", "ボリューム",
      ("light", "軽め", ["a small light portion of food"]),
      ("normal", "普通", ["a normal sized portion of food"]),
      ("heavy", "がっつり", ["a huge pile of food, very large portion"]),
      requires=("isfood", ['yes'])),
    q("veg", "野菜",
      ("yes", "野菜がある", ["a dish with plenty of fresh vegetables and salad"]),
      ("no", "野菜が見えない", ["a dish of only meat and carbohydrates, no vegetables"]),
      requires=("isfood", ['yes'])),
    q("plating", "盛り付け",
      ("nice", "きれい", ["beautifully plated food at a restaurant, styled"]),
      ("casual", "普段のごはん", ["a casual home cooked meal, plain plating"]),
      requires=("isfood", ['yes'])),
    q("where", "場所",
      ("restaurant", "店", ["food served at a restaurant table"]),
      ("home", "家", ["a home kitchen or dining table"]),
      ("outdoor", "屋外", ["food eaten outdoors, picnic or barbecue"]),
      requires=("isfood", ['yes'])),
]

# ---------------------------------------------------------------- 5. ペット
PET = [
    q("animal", "動物",
      ("dog", "犬", ["a photo of a dog", "a puppy"]),
      ("cat", "猫", ["a photo of a cat", "a kitten"]),
      ("other", "その他の動物", ["a photo of a bird, rabbit or other small pet"]),
      ("none", "動物はいない", ["a scene with no animals"])),
    q("doing", "していること",
      ("sleep", "寝ている", ["a sleeping animal with eyes closed, curled up"]),
      ("play", "遊んでいる", ["an animal playing energetically with a toy"]),
      ("eat", "食べている", ["an animal eating from a bowl"]),
      ("stare", "こちらを見ている", ["an animal staring straight at the camera"]),
      requires=("animal", ['dog', 'cat', 'other'])),
    q("mood", "機嫌",
      ("happy", "ごきげん", ["a happy relaxed pet, tail up, bright eyes"]),
      ("calm", "落ち着いている", ["a calm resting pet"]),
      ("annoyed", "不満そう", ["an annoyed grumpy animal, ears back"]),
      requires=("animal", ['dog', 'cat', 'other'])),
    q("place", "場所",
      ("indoor", "室内", ["a pet indoors on a sofa or floor"]),
      ("outdoor", "屋外", ["a pet outdoors on grass or a street"]),
      requires=("animal", ['dog', 'cat', 'other'])),
    q("count", "頭数",
      ("one", "1 匹", ["a single animal alone"]),
      ("many", "複数", ["several animals together"]),
      requires=("animal", ['dog', 'cat', 'other'])),
    q("closeup", "寄り引き",
      ("close", "顔のアップ", ["an extreme close up of an animal face"]),
      ("full", "全身", ["a full body shot of an animal"]),
      requires=("animal", ['dog', 'cat', 'other'])),
]

# ---------------------------------------------------------------- 6. 服装
FASHION = [
    q("person", "人が写っているか",
      ("yes", "写っている", ["a full body photo of a person wearing clothes"]),
      ("no", "写っていない", ["a scene with no people"])),
    q("formal", "フォーマル度",
      ("formal", "きちんと", ["a person in a business suit and tie, formal wear"]),
      ("smart", "きれいめ", ["a person in smart casual clothes, jacket and shirt"]),
      ("casual", "カジュアル", ["a person in a t-shirt and jeans, casual wear"]),
      ("sport", "スポーツ", ["a person in athletic sportswear and sneakers"]),
      requires=("person", ['yes'])),
    q("season", "季節感",
      ("summer", "夏物", ["summer clothes, short sleeves and shorts"]),
      ("mid", "春秋物", ["light jacket or long sleeves, mild weather clothing"]),
      ("winter", "冬物", ["winter clothes, thick coat scarf and gloves"]),
      requires=("person", ['yes'])),
    q("tone", "色",
      ("dark", "暗い色", ["clothes in dark black and navy tones"]),
      ("bright", "明るい色", ["clothes in bright vivid colours"]),
      ("neutral", "淡い色", ["clothes in soft beige and pastel tones"]),
      requires=("person", ['yes'])),
    q("outer", "上着",
      ("yes", "着ている", ["a person wearing a coat or jacket"]),
      ("no", "着ていない", ["a person in only a shirt, no outer layer"]),
      requires=("person", ['yes'])),
    q("pattern", "柄",
      ("plain", "無地", ["plain clothes with no pattern"]),
      ("pattern", "柄物", ["clothes with a bold pattern, stripes or print"]),
      requires=("person", ['yes'])),
]

# ---------------------------------------------------------------- 7. 写真の出来
PHOTO = [
    q("focus", "ピント",
      ("sharp", "合っている", ["a sharp well focused photo with crisp detail"]),
      ("blur", "ぼけている", ["a blurry out of focus photo", "a motion blurred shaky photo"])),
    q("exposure", "明るさ",
      ("ok", "適正", ["a well exposed photo with balanced brightness"]),
      ("dark", "暗い", ["an underexposed photo, too dark to see"]),
      ("bright", "明るすぎ", ["an overexposed photo, blown out white highlights"])),
    q("backlight", "逆光",
      ("yes", "逆光", ["a backlit photo with the subject dark against a bright window"]),
      ("no", "順光", ["a photo with even front lighting"])),
    q("tilt", "傾き",
      ("level", "水平", ["a photo with a level straight horizon"]),
      ("tilted", "傾いている", ["a photo with a noticeably tilted crooked horizon"])),
    q("subject", "主題",
      ("clear", "はっきりしている", ["a photo with one clear main subject in the centre"]),
      ("unclear", "ばらけている", ["a cluttered photo with no clear subject"])),
    q("distance", "寄り引き",
      ("close", "寄り", ["an extreme close up macro shot"]),
      ("mid", "中くらい", ["a medium shot of a subject"]),
      ("wide", "引き", ["a wide landscape shot showing a whole scene"])),
    q("noise", "画質",
      ("clean", "きれい", ["a clean noise free photo"]),
      ("noisy", "ざらつき", ["a grainy noisy photo taken in low light"])),
]

# ---------------------------------------------------------------- 8. 河川カメラの監視
KASEN = [
    q("flood", "水の広がり",
      ("normal", "平常 (河原が見えている)", ["a river in normal condition with dry riverbank and gravel visible",
                                     "a calm narrow river between wide dry banks",
                                     "a night view of a river with dry banks"]),
      ("high", "増水 (河原が水に浸かる)", ["a swollen river with high muddy water covering the riverbank",
                                  "a river in flood with fast brown water near the top of the bank"]),
      ("flood", "一面が水", ["a flooded area completely covered by water, overflowing river",
                        "farmland and roads submerged under flood water"]),
      ("unknown", "暗くて判別できない", ["a dark night camera view where the water level cannot be judged",
                                "a green infrared night camera image of grass and bushes",
                                "a night image too dark to tell where the water is"])),
    q("turbid", "水の濁り",
      ("clear", "澄んでいる", ["a river with clear blue green water", "clean transparent river water"]),
      ("muddy", "濁っている", ["a river with brown muddy turbid water", "chocolate brown flood water"]),
      ("nowater", "水面が見えない", ["a scene without any water surface", "a view of grass and road with no river visible",
                             "a dark night scene where the water cannot be seen"])),
    q("weather", "天気",
      ("sunny", "晴れ", ["an outdoor scene on a sunny day with blue sky and shadows", "bright sunshine outdoors"]),
      ("cloudy", "曇り", ["an outdoor scene on a cloudy overcast grey day", "flat grey sky over a landscape"]),
      ("rain", "雨", ["an outdoor scene during rain, wet surfaces and raindrops", "heavy rain falling outdoors"]),
      ("snow", "雪", ["an outdoor scene covered with snow", "snow falling over a landscape"])),
    q("time", "明るさ",
      ("day", "昼", ["an outdoor scene in bright daylight", "a daytime landscape photo"]),
      ("dusk", "薄暮", ["an outdoor scene at dusk or dawn, dim orange light", "twilight over a river"]),
      ("night", "夜", ["an outdoor scene at night, dark with artificial lights",
                     "a dark night surveillance image with street lights",
                     "a night time camera view, mostly black with a few lights"])),
    q("visibility", "見通し",
      ("clear", "良好", ["a clear sharp outdoor view with good visibility",
                      "a sharp night camera view where the scene is recognisable"]),
      ("fog", "霧・もや", ["an outdoor scene covered in fog or haze with poor visibility", "thick fog hiding the background"]),
      ("drops", "レンズに水滴・汚れ", ["a camera image blurred by water droplets on the lens",
                             "a dirty smeared camera lens blurring the whole picture"])),
    q("signal", "映像の状態",
      ("ok", "正常", ["a normal outdoor surveillance camera image in daylight",
                   "a normal night surveillance camera image, dark but recognisable",
                   "a usable security camera picture of an outdoor scene"]),
      ("black", "真っ黒・無信号", ["a completely black image with no signal", "a blank empty frame, no picture"]),
      ("noise", "乱れ・ノイズ", ["a broken video image with static noise and colour bands",
                          "a glitched distorted video frame with torn lines"])),
    q("debris", "漂流物",
      ("none", "見当たらない", ["a river surface with nothing floating on it", "an empty water surface"]),
      ("debris", "流木・ごみが見える", ["driftwood, logs and debris floating on a river",
                              "branches and rubbish carried by flood water"]),
      ("unknown", "暗くて判別できない", ["a dark night camera view where the water surface cannot be inspected",
                                "a green infrared night camera image with no visible water surface"])),
    q("people", "人・車",
      ("none", "いない", ["an outdoor scene with no people and no vehicles", "an empty riverside with nobody around"]),
      ("people", "人がいる", ["an outdoor scene with people walking", "people standing near a river"]),
      ("vehicle", "車がいる", ["an outdoor scene with cars or trucks", "vehicles driving on a road"])),
    q("structure", "写っているもの",
      ("bridge", "橋", ["a bridge over a river", "a long road bridge crossing water"]),
      ("weir", "堰・水門", ["a weir, floodgate or sluice on a river", "concrete flood gates on a waterway"]),
      ("bank", "堤防・河川敷", ["an embankment and open riverbank without structures",
                          "grass covered flood plain beside a river"])),
]

# ---------------------------------------------------------------- 9. 工事・作業現場
SITE = [
    q("issite", "現場か",
      ("yes", "工事・作業現場", ["a construction site with machinery and materials", "workers building a structure"]),
      ("no", "現場ではない", ["an ordinary street or room, not a construction site"])),
    q("worker", "作業者",
      ("none", "いない", ["a construction site with no workers present"]),
      ("one", "1 人", ["a single worker at a site"]),
      ("many", "複数", ["several workers at a site"]),
      requires=("issite", ['yes'])),
    q("helmet", "保護具",
      ("yes", "着用している", ["a worker wearing a safety helmet and high visibility vest"]),
      ("no", "着用していない", ["a person at a site without a helmet, in ordinary clothes"]),
      ("noperson", "人がいない", ["a site with nobody in the picture"]),
      requires=("issite", ['yes'])),
    q("machine", "重機",
      ("yes", "動いている", ["an excavator or crane operating at a site"]),
      ("idle", "止まっている", ["heavy machinery parked and idle at a site"]),
      ("none", "重機なし", ["a site with no heavy machinery"]),
      requires=("issite", ['yes'])),
    q("scaffold", "足場・仮設",
      ("yes", "組んである", ["scaffolding erected around a building"]),
      ("no", "無い", ["a site with no scaffolding"]),
      requires=("issite", ['yes'])),
    q("barrier", "規制",
      ("yes", "規制している", ["traffic cones and barriers closing off an area", "a fenced off work zone with signs"]),
      ("no", "していない", ["an open area with no barriers"]),
      requires=("issite", ['yes'])),
    q("progress", "進み具合",
      ("ground", "更地・基礎", ["bare ground or foundation work at a construction site"]),
      ("frame", "躯体", ["a building frame under construction, structure visible"]),
      ("finish", "仕上げ", ["a nearly finished building with facade in place"]),
      requires=("issite", ['yes'])),
    q("timesite", "時間帯",
      ("day", "昼", ["a construction site in daylight"]),
      ("night", "夜", ["a construction site at night under floodlights"]),
      requires=("issite", ['yes'])),
]

# ---------------------------------------------------------------- 10. 道路・交通
TRAFFIC = [
    q("isroad", "道路か",
      ("yes", "道路", ["a road or street seen from a traffic camera"]),
      ("no", "道路ではない", ["an indoor scene, not a road"])),
    q("jam", "混み具合",
      ("empty", "空いている", ["an empty road with no cars"]),
      ("light", "流れている", ["a road with a few cars moving freely"]),
      ("jam", "渋滞", ["a traffic jam with a long queue of stopped cars, bumper to bumper"]),
      requires=("isroad", ['yes'])),
    q("surface", "路面",
      ("dry", "乾いている", ["a dry road surface"]),
      ("wet", "濡れている", ["a wet road with puddles and reflections after rain"]),
      ("snow", "雪・凍結", ["a snow covered icy road"]),
      requires=("isroad", ['yes'])),
    q("weather", "天気",
      ("clear", "晴れ・曇り", ["a road under a clear or cloudy sky"]),
      ("rain", "雨", ["a road during rainfall"]),
      ("fog", "霧", ["a road in thick fog with poor visibility"]),
      requires=("isroad", ['yes'])),
    q("timeroad", "時間帯",
      ("day", "昼", ["a road in bright daylight"]),
      ("night", "夜", ["a road at night with headlights and street lamps"]),
      requires=("isroad", ['yes'])),
    q("vehicle", "車種",
      ("car", "乗用車が中心", ["a road with mostly passenger cars"]),
      ("truck", "大型車が目立つ", ["a road with large trucks and buses"]),
      ("none", "車がいない", ["a road with no vehicles"]),
      requires=("isroad", ['yes'])),
    q("work", "工事・規制",
      ("yes", "規制あり", ["road works with cones and a lane closure"]),
      ("no", "規制なし", ["a normal open road with no works"]),
      requires=("isroad", ['yes'])),
    q("incident", "異常",
      ("none", "見当たらない", ["a normal road scene with nothing unusual"]),
      ("stopped", "停車・事故らしきもの", ["a broken down or crashed car stopped on the road with hazard lights"]),
      requires=("isroad", ['yes'])),
]

#: key -> (画面に出す名前, 質問)
QUESTION_SETS: dict[str, tuple[str, list[Q]]] = {
    "general": ("室内外の汎用", GENERAL),
    "people": ("人物の様子", PEOPLE),
    "game": ("ゲーム画面の状態", GAME),
    "food": ("食べ物", FOOD),
    "pet": ("ペット", PET),
    "fashion": ("服装", FASHION),
    "photo": ("写真の出来", PHOTO),
    "kasen": ("河川カメラの監視", KASEN),
    "site": ("工事・作業現場", SITE),
    "traffic": ("道路・交通", TRAFFIC),
}
